feat: update Bitbucket pipeline to handle both firmware.bin and littlefs.bin

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -12,10 +12,10 @@ pipelines:
             # Fetch the version from version.txt
             - VERSION_FILE="version.txt"
             - if [ -f "$VERSION_FILE" ]; then
-                VERSION=$(cat $VERSION_FILE);
+              VERSION=$(cat $VERSION_FILE);
               else
-                echo "version.txt file not found!";
-                exit 1;
+              echo "version.txt file not found!";
+              exit 1;
               fi
             - echo "Current version = $VERSION"
 
@@ -23,31 +23,40 @@ pipelines:
             - RESPONSE=$(curl -s -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads")
 
             # Parse the latest file uploaded
-            - LATEST_FILE=$(echo "$RESPONSE" | jq -r '.values | sort_by(.created_on) | last(.[]).name')
-            - echo "Latest uploaded file = $LATEST_FILE"
+            - LATEST_FILES=$(echo "$RESPONSE" | jq -r '.values | sort_by(.created_on) | last(.[]).name')
+            - echo "Latest uploaded files = $LATEST_FILES"
 
             # Check if the latest file matches the current version's binary
-            - FILE_NAME="${VERSION}.bin"
-            - if [ "$LATEST_FILE" = "$FILE_NAME" ]; then
-                echo "Binary file ${FILE_NAME} already exists as the latest upload. Skipping upload.";
-                exit 0;
+            - FIRMWARE_BIN="${VERSION}_firmware.bin"
+            - LITTLEFS_BIN="${VERSION}_littlefs.bin"
+
+            - if echo "$LATEST_FILES" | grep -q "$FIRMWARE_BIN" && echo "$LATEST_FILES" | grep -q "$LITTLEFS_BIN"; then
+              echo "Both binary files already exist as the latest upload. Skipping upload.";
+              exit 0;
               fi
 
             # Run PlatformIO build
             - platformio run
+            - platformio --target buildfs
 
-            # Find the generated binary file
-            - PLATFORMIO_BIN=$(find .pio -name "*.bin" | head -n 1)
-            - echo "Binary file generated $PLATFORMIO_BIN"
+            # Find the generated binary files
+            - FIRMWARE_PATH=$(find .pio -name "firmware.bin" | head -n 1)
+            - LITTLEFS_PATH=$(find .pio -name "littlefs.bin" | head -n 1)
 
-            # Upload the binary to Bitbucket Downloads section
-            - |
-              if [ -f "$PLATFORMIO_BIN" ]; then
-                echo "Uploading binary file: ${FILE_NAME}"
-                curl -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" \
-                  -X POST "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads" \
-                  -F "files=@$PLATFORMIO_BIN;filename=${FILE_NAME}"
-              else
-                echo "Binary file not found!"
-                exit 1
+            # Check if both files were generated
+            - if [ ! -f "$FIRMWARE_PATH" ] || [ ! -f "$LITTLEFS_PATH" ]; then
+              echo "One or both binary files not found!"
+              exit 1
               fi
+
+            # Upload firmware.bin
+            - echo "Uploading firmware $FIRMWARE_BIN"
+            - curl -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" \
+              -X POST "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads" \
+              -F "files=@$FIRMWARE_PATH;filename=${FIRMWARE_BIN}"
+
+            # Upload littlefs.bin
+            - echo "Uploading LittleFS $LITTLEFS_BIN"
+            - curl -u "$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD" \
+              -X POST "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_WORKSPACE/$BITBUCKET_REPOSITORY/downloads" \
+              -F "files=@$LITTLEFS_PATH;filename=${LITTLEFS_BIN}"
